### ISSUE TITLE
ImportError: cannot import name match_hostname

### ISSUE THREAD

**Issue by Kyle-Falconer** [TkTech/ckanext-cloudstorage#10]
I'm trying to get this plugin working with [VTA's Open Data Portal](https://github.com/vta/Open-Data-Portal) project, which uses Docker containers for deployment.

In the [CKAN Dockerfile](https://github.com/vta/Open-Data-Portal/blob/master/ckan/Dockerfile), I'm using the following commands to try to install cloudstorage:

```
# download CKAN + dependencies
...

# cloudstorage plugin
# there are no release labels for this, so work only on a known-good commit
WORKDIR /usr/lib/ckan/
RUN pip install 'apache-libcloud==1.5.0'
RUN git clone https://github.com/open-data/ckanext-cloudstorage.git
WORKDIR /usr/lib/ckan/ckanext-cloudstorage/
RUN git checkout d354fc752a9d501a3f4696295a83794393e447fe
RUN python setup.py install

# run CKAN
...
```

I've put the appropriate settings in the CKAN settings file:

```
## cloudstorage - Amazon S3
ckanext.cloudstorage.driver = S3_US_WEST_OREGON
ckanext.cloudstorage.container_name = odp_uploads
ckanext.cloudstorage.driver_options = {"key": "<redacted>", "secret": "<redacted>"}
```

Now, when I try to upload a file as a resource, I get a crash with the following trace:

```
Error - <type 'exceptions.ImportError'>: cannot import name match_hostname
URL: http://ec2-54-186-135-205.us-west-2.compute.amazonaws.com/dataset/new_resource/test6
sys.path: [
    '/usr/lib/ckan/default/src/ckan/ckan',
    '/usr/local/bin',
    '/usr/lib/python2.7',
    '/usr/lib/python2.7/plat-x86_64-linux-gnu',
    '/usr/lib/python2.7/lib-tk',
    '/usr/lib/python2.7/lib-old',
    '/usr/lib/python2.7/lib-dynload',
    '/usr/local/lib/python2.7/dist-packages',
    '/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg',
    '/usr/lib/ckan/default/src/ckan',
    '/usr/local/lib/python2.7/dist-packages/ckanext_mapviews-0.1-py2.7.egg',
    '/usr/local/lib/python2.7/dist-packages/ckanext_cloudstorage-0.1.0-py2.7.egg',
    '/usr/lib/python2.7/dist-packages']
File '/usr/local/lib/python2.7/dist-packages/weberror/errormiddleware.py', line 171 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/python2.7/dist-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/python2.7/dist-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware/pylons_app.py', line 245 in inner
  result = application(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/local/lib/python2.7/dist-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 292 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/package.py', line 685 in new_resource
  get_action('resource_create')(context, data)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 431 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py', line 297 in resource_create
  upload = uploader.get_resource_uploader(data_dict)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/uploader.py', line 38 in get_resource_uploader
  upload = plugin.get_resource_uploader(data_dict)
File '/usr/local/lib/python2.7/dist-packages/ckanext_cloudstorage-0.1.0-py2.7.egg/ckanext/cloudstorage/plugin.py', line 53 in get_resource_uploader
  return storage.ResourceCloudStorage(data_dict)
File '/usr/local/lib/python2.7/dist-packages/ckanext_cloudstorage-0.1.0-py2.7.egg/ckanext/cloudstorage/storage.py', line 137 in __init__
  super(ResourceCloudStorage, self).__init__()
File '/usr/local/lib/python2.7/dist-packages/ckanext_cloudstorage-0.1.0-py2.7.egg/ckanext/cloudstorage/storage.py', line 22 in __init__
  self.driver_name
File '/usr/local/lib/python2.7/dist-packages/libcloud/storage/providers.py', line 78 in get_driver
  deprecated_constants=deprecated_constants)
File '/usr/local/lib/python2.7/dist-packages/libcloud/common/providers.py', line 72 in get_driver
  _mod = __import__(mod_name, globals(), locals(), [driver_name])
File '/usr/local/lib/python2.7/dist-packages/libcloud/storage/drivers/s3.py', line 37 in <module>
  from libcloud.common.base import ConnectionUserAndKey, RawResponse
File '/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py', line 53 in <module>
  from libcloud.httplib_ssl import LibcloudHTTPConnection
File '/usr/local/lib/python2.7/dist-packages/libcloud/httplib_ssl.py', line 33 in <module>
  from libcloud.utils.py3 import match_hostname
ImportError: cannot import name match_hostname
```

Is there a particular version of libcloud that is known to work with this plugin? From the trace, it seems like it's trying to access `match_hostname` from `libcloud.utils.py3`, and if the filename is any indication, I don't know that it will work with Python 2.7 (as required by CKAN).

**Comment by Kyle-Falconer** [comment]
This seems to be working with version 1.2.1, but then it requires `backports.ssl_match_hostname` to also be installed.

The following Dockerfile section works:

```
# cloudstorage plugin
# there are no release labels for this, so work only on a known-good commit
WORKDIR /usr/lib/ckan/
RUN pip install 'apache-libcloud==1.2.1'
RUN pip install 'backports.ssl_match_hostname==3.5.0.1'
RUN git clone https://github.com/open-data/ckanext-cloudstorage.git
WORKDIR /usr/lib/ckan/ckanext-cloudstorage/
RUN git checkout d354fc752a9d501a3f4696295a83794393e447fe
RUN python setup.py install
```

Perhaps the readme should be updated to reflect the versions of the dependencies.
